#__________Dmitriy Kalistratov production__________
#________________Github Action________________
name: My-GitHubActions-Basics
env:
  APPLICATION_NAME    : "MyFlask"
  DEPLOY_PACKAGE_NAME : "flask-deploy-ver-${{ github.sha }}"

on:
  push: 
    branches: 
      - main

jobs:
  my-testing: 
    runs-on: ubuntu-latest
    
    steps:
    - name: Print Hello Message
      run: echo "Hello World from Testing job"
      
    - name: Execure few commands
      run: |
        echo "Hello Message 1"
        echo "Hello Message 1"
        echo "Application name ${{ env.APPLICATION_NAME }}"


  my-deploy:
    runs-on: ubuntu-latest
    needs: [my-testing]
    
    steps:
    - name: Print Hello Message
      run: echo "Hello World from Deploy job"

    - name: Printinf Deployment Package
      run: echo "Deploy package name is ${{ env.DEPLOY_PACKAGE_NAME }}"
     
