#__________Dmitriy Kalistratov production__________
#________________Github Action________________
name: My-GitHubActions-Basics
env:
  APPLICATION_NAME    : "MyFlask"
  DEPLOY_PACKAGE_NAME : "flask-deploy-ver-${{ github.sha }}"

on:
  push: 
    branches: 
      - main

jobs:
  my-testing: 
    runs-on: ubuntu-latest
    
    steps:
    - name: Print Hello Message
      run : echo "Hello World from Testing job"
      
    - name: Execure few commands
      run : |
        echo "Hello Message 1"
        echo "Hello Message 1"
        echo "Application name ${{ env.APPLICATION_NAME }}"

    - name: List corrent folder
      run : ls -la

    - name: Git clone my repo
      uses: actions/checkout@v1

    - name: List corrent folder
      run : ls -la


  my-deploy:
    runs-on: ubuntu-latest
    needs: [my-testing]
    
    steps:
    - name: Print Hello Message
      run : echo "Hello World from Deploy job"

    - name: Printinf Deployment Package
      run : echo "Deploy package name is ${{ env.DEPLOY_PACKAGE_NAME }}"

    - name: Lets test some packages if they are here 1
      run : aws --version

    - name: Lets test some packages if they are here 2
      run : zip
     
